services:
  scheduler:
    volumes:
      - ./dbt/2_dw/prj_dw:/usr/local/airflow/dbt/prj_dw
  dag-processor:
    volumes:
      - ./dbt/2_dw/prj_dw:/usr/local/airflow/dbt/prj_dw


networks:
  airflow:
    external: true
    name: airflow